export const profile = {
  name: "李继潇",
  englishName: "Jixiao Li",
  affiliation: "北海道大学农学院",
  affiliationEnglish: "Graduate School of Agriculture, Hokkaido University",
  email: "yuriljx@gmail.com",
  scholarUrl: "https://scholar.google.com/citations?user=m2FLOrUAAAAJ&hl=zh-CN",
  githubUrl: "https://github.com/yuriljx",
};

export const researchFocus = [
  {
    code: "01",
    title: "作物表型与品质",
    english: "Crop phenotyping & quality",
    description: "从田间影像、实验测量与时间序列中提取可解释的作物性状。",
  },
  {
    code: "02",
    title: "育种与培养体系",
    english: "Breeding & culture systems",
    description: "关注倍性变化、花药培养与非孟德尔恢复偏倚等育种问题。",
  },
  {
    code: "03",
    title: "研究软件与证据",
    english: "Research software & evidence",
    description: "以可追溯数据结构、审计边界和可复现流程支撑研究判断。",
  },
];

export const publications = [
  {
    year: "2026",
    title: "Feature extraction based on RGB images for rapid and non-destructive estimation of haskap fruit quality attributes",
    authors: "J. Zhang, J. Li, X. Meng, Y. Yang, Y. Lyu, Y. Hoshino",
    venue: "Postharvest Biology and Technology, 240, 114416",
    label: "Computer Vision",
    thumb: "/research/haskap-fruit.webp",
    thumbAlt: "蓝靛果研究材料",
  },
  {
    year: "2026",
    title: "Monitoring Relative Grape Berry Growth in the Field with YOLOv8 and Biology-informed Smoothing",
    authors: "J. Li, T. Sone, X. Meng, K. Hirayama, M. Ikuta, Y. Inose, Y. Hoshino",
    venue: "The Horticulture Journal, SZD-110",
    label: "Field Phenotyping",
    thumb: "/software/grape/mature-stage.webp",
    thumbAlt: "葡萄田间时间序列材料",
  },
  {
    year: "2026",
    title: "YOLO-APPLE: Accurate Identification of Apple Cultivars Using an Improved YOLOv7 Framework",
    authors: "J. Zhang, X. Meng, J. Li, Y. Hoshino",
    venue: "The Horticulture Journal, SZD-115",
    label: "Cultivar Detection",
    thumb: null,
    thumbAlt: "计算机视觉论文标识",
    thumbCode: "CV / 26",
  },
  {
    year: "2025",
    title: "Exploring the impact of ploidy levels on fruit attributes of haskap",
    authors: "J. Li, Y. Hoshino",
    venue: "Euphytica, 221(6), 74",
    label: "Polyploid Breeding",
    thumb: "/research/haskap-field.webp",
    thumbAlt: "蓝靛果田间材料",
  },
  {
    year: "2024",
    title: "Elucidating the impact of ploidy level on biochemical content accumulation in haskap fruits: A comprehensive approach for fruit assessment",
    authors: "J. Li, Y. Hoshino",
    venue: "Scientia Horticulturae, 327, 112831",
    label: "Fruit Biochemistry",
    thumb: "/research/haskap-fruit.webp",
    thumbAlt: "蓝靛果果实材料",
  },
  {
    year: "2023",
    title: "Phenotypic analysis of polyploid and aneuploid haskap plants and their progeny production",
    authors: "J. Li, Y. Suzuki, Y. Hoshino",
    venue: "Euphytica, 219(5), 52",
    label: "Plant Phenotyping",
    thumb: "/research/haskap-field.webp",
    thumbAlt: "蓝靛果田间材料",
  },
  {
    year: "2016",
    title: "Addressing the ice nucleating abilities of marine aerosol: A combination of deposition mode laboratory and field measurements",
    authors: "L. A. Ladino, J. D. Yakobi-Hancock, W. P. Kilthau, R. H. Mason, M. Si, J. Li, et al.",
    venue: "Atmospheric Environment, 132, 1–10",
    label: "Atmospheric Chemistry",
    thumb: null,
    thumbAlt: "大气化学论文标识",
    thumbCode: "ATM / 16",
  },
  {
    year: "2015",
    title: "Ice nucleating particles at a coastal marine boundary layer site: correlations with aerosol type and meteorological conditions",
    authors: "R. H. Mason, M. Si, J. Li, C. Chou, R. Dickie, D. Toom-Sauntry, et al.",
    venue: "Atmospheric Chemistry and Physics, 15(21), 12547–12566",
    label: "Bioaerosol",
    thumb: null,
    thumbAlt: "冰核气溶胶论文标识",
    thumbCode: "ICE / 15",
  },
];

export const presentations = [
  {
    year: "2025",
    event: "第十届中国国际人工智能峰会暨算力算法大会（CIAI）",
    title: "用于食品质量评估的计算代谢组学端到端 AI 管线",
    format: "口头报告",
  },
  {
    year: "2024",
    event: "第十五届国际计算系统生物学会议（ISB）",
    title: "基于田间图像和时间序列的多模态机器学习预测果实糖度与有机酸",
    format: "口头报告",
  },
  {
    year: "2023",
    event: "第 103 届日本化学会（CSJ）年会",
    title: "活化 MSTFA 硅烷化反应增强植物基质中酚类和有机酸的 GC-MS 定量分析",
    format: "口头报告",
  },
  {
    year: "2022",
    event: "日本园艺学会（JSHS）秋季会议",
    title: "多倍体蓝靛果果实中糖类和有机酸的 GC-MS 分析",
    format: "口头报告",
  },
];

export const softwareProjects = [
  {
    slug: "p2-record",
    title: "P2 Rice DH Record System",
    subtitle: "花药培养实验记录与谱系追踪",
    status: "LOCAL APPLICATION · v0.5.12",
    description: "围绕播种、采穗、低温处理、花药培养、再生与倍性判定组织实验记录；计划值、实际值、来源批次和审计记录保留在同一条可追溯链路中。",
    features: ["计划与实际", "谱系追踪", "库存约束", "本地 SQLite"],
    boundary: "展示真实本地界面；截图中的记录仅用于说明工作流，不作为研究结论。",
    link: null,
    visuals: [
      { kind: "image", src: "/software/p2/dashboard.png", alt: "P2 水稻加倍单倍体记录系统首页", caption: "工作流首页与本地运行边界", position: "top" },
      { kind: "image", src: "/software/p2/workflow.png", alt: "花药批次与培养处理臂界面", caption: "花药批次、来源穗批次与培养处理臂", position: "top" },
      { kind: "image", src: "/software/p2/lineage.png", alt: "谱系查询界面", caption: "按核心 ID 检索上游与下游谱系", position: "top" },
    ],
  },
  {
    slug: "genome-finder",
    title: "Rice Genome Resource Finder",
    subtitle: "水稻公共基因组资源筛选与审计",
    status: "INTERNAL BETA · v7.9.8",
    description: "从品种名与别名出发，跨 NCBI Assembly、SRA、BioSample、ENA 与 DDBJ 检索公开资源，合并重复 accession，并输出保留证据与警告的审计工作簿。",
    features: ["别名扩展", "多库检索", "身份证据", "审计工作簿"],
    boundary: "这是筛选与分流工具；发表、批量下载或品种级结论前仍须核对原始元数据。",
    link: null,
    visuals: [
      { kind: "image", src: "/software/genome/overview.png", alt: "水稻基因组资源检索工具首页", caption: "输入模板、数据库范围与工具边界", position: "top" },
      { kind: "image", src: "/software/genome/options.png", alt: "水稻基因组资源筛选参数", caption: "连接器、平台兼容性与保守排序逻辑", position: "center" },
      { kind: "panel", panel: "audit-workbook", caption: "输出结构示意：摘要、候选、输入质控与来源审计" },
    ],
  },
  {
    slug: "trait-tool",
    title: "Aphros Trait Tool",
    subtitle: "水稻品种性状证据库",
    status: "LOCAL EVIDENCE TOOL · v0.8.4",
    description: "将品种卡、性状检索、来源追踪、双品种对比、数据覆盖率与校订队列集中到本地界面，并把“无记录”与“无性状”严格分开。",
    features: ["品种卡", "证据对比", "来源追踪", "校订队列"],
    boundary: "默认展示已验证记录；探索与假设模块不构成最终育种决策依据。",
    link: null,
    visuals: [
      { kind: "image", src: "/software/trait/home.png", alt: "Aphros 性状工具首页", caption: "品种检索、性状覆盖与证据规模", position: "top" },
      { kind: "image", src: "/software/trait/dashboard.png", alt: "Aphros 性状数据概览", caption: "覆盖率、缺口和下一轮数据补充优先级", position: "top" },
      { kind: "image", src: "/software/trait/compare.png", alt: "两个水稻品种的证据对比", caption: "Yumepirika 与越光的逐性状证据对比", position: "top" },
    ],
  },
  {
    slug: "riceperturbnet",
    title: "RicePerturbNet",
    subtitle: "公共数据整合与候选证据分层",
    status: "INTERNAL RESEARCH FRAMEWORK",
    description: "整合公开转录组、繁殖组织语境、调控因子先验与外部证据，对候选关系进行分层、审计和适用范围控制。",
    features: ["公共数据", "细胞类型语境", "证据分层", "声明门控"],
    boundary: "当前关系是非因果候选边；不代表直接 TF–target 结合，也不支持虚拟扰动。",
    link: null,
    visuals: [
      { kind: "image", src: "/software/riceperturb/framework.png", alt: "RicePerturbNet 研究框架", caption: "从公开数据到候选层、评估门与证据缺口", position: "center" },
      { kind: "image", src: "/software/riceperturb/candidate-network.png", alt: "候选关系网络与证据摘要", caption: "限定语境的候选关系与证据层级", position: "center" },
      { kind: "image", src: "/software/riceperturb/evidence-gaps.png", alt: "候选方向的证据层与缺口", caption: "证据层、未覆盖来源与明确的声明边界", position: "center" },
    ],
  },
  {
    slug: "stride-dh",
    title: "STRIDE-DH",
    subtitle: "水稻花药培养 DH 群体恢复偏倚框架",
    status: "CONDITIONAL FEASIBILITY · v0.1.1",
    description: "围绕水稻花药培养来源加倍单倍体群体中的非孟德尔等位恢复，建立可证伪的终点净恢复偏倚模型，并审计样本依赖与数据可用性。",
    features: ["公开矩阵 QC", "恢复偏倚", "依赖审计", "可复现测试"],
    boundary: "目前为 Week 1 YELLOW：条件可行；不是候选基因工具，也没有已完成的图形界面或完整层级模型。",
    link: null,
    visuals: [
      { kind: "panel", panel: "stride-inventory", caption: "已获取并结构核验的两套公开矩阵" },
      { kind: "panel", panel: "stride-dependence", caption: "Sun 2023 样本依赖审计；连通分量不等于有效样本量" },
      { kind: "panel", panel: "stride-smoke", caption: "内置合成夹具的 QC 烟雾测试；不含研究数据" },
    ],
  },
  {
    slug: "grape-length",
    title: "Grape Length",
    subtitle: "田间葡萄果粒生长监测",
    status: "PUBLIC REPOSITORY",
    description: "用带尺度参照的田间影像估计果粒相对尺寸，构建跨日期的样本时间序列，并通过生物学约束平滑减少检测波动对生长曲线的影响。",
    features: ["目标检测", "尺度参照", "时间序列", "生物学平滑"],
    boundary: "展示真实田间采样照片与既有分析图；曲线属于相关实验材料，不外推到未观测样本。",
    link: "https://github.com/yuriljx/Grape_Length",
    visuals: [
      { kind: "image", src: "/software/grape/early-stage.webp", alt: "葡萄 Z5 样本早期田间图像", caption: "Z5 时间序列早期：带尺度与色彩参照的田间采样", position: "center" },
      { kind: "image", src: "/software/grape/mature-stage.webp", alt: "葡萄 Z5 样本成熟期田间图像", caption: "同一样本成熟期影像，保留田间环境与尺度参照", position: "center" },
      { kind: "image", src: "/software/grape/growth-curve.png", alt: "葡萄平均果粒直径时间序列", caption: "组合样本的平均果粒直径与生物学约束平滑", position: "center" },
    ],
  },
] as const;

export const researchProjects = [
  {
    code: "A",
    title: "倍性、果实表型与生化品质",
    description: "围绕蓝靛果倍性变化，连接果实形态、糖与有机酸等品质信息。",
    tags: ["Ploidy", "Fruit quality", "GC–MS"],
  },
  {
    code: "B",
    title: "田间视觉与非破坏估计",
    description: "将目标检测、RGB 特征和时间序列用于葡萄、苹果及蓝靛果的表型研究。",
    tags: ["Computer vision", "Time series", "Field imaging"],
  },
  {
    code: "C",
    title: "水稻培养体系与实验数据链",
    description: "把花药培养、批次来源、处理臂和倍性判定组织为可追溯的实验记录。",
    tags: ["Anther culture", "DH", "Provenance"],
  },
  {
    code: "D",
    title: "公共组学数据与声明控制",
    description: "在水稻公共数据整合、候选证据分层和样本依赖审计中明确可支持与不可支持的结论。",
    tags: ["Public data", "Evidence audit", "Reproducibility"],
  },
];
